---
- name: "exec : kubectl : Execute the native kubectl command"
  ansible.builtin.shell:
    cmd: |-
      {{ sc_okd_bin_directory }}/kubectl-v{{ sc_okd_release }}-{{ sc_okd_release_minor }} {{ sc_okd_exec_cmd | default("version") }}
    executable: /bin/bash
    chdir: "{{ sc_okd_exec_path | default(omit) }}"
  register: sc_okd_exec_kubectl_return