---
- name: "exec : oc : Execute the native oc command"
  ansible.builtin.shell:
    cmd: |-
      {{ sc_okd_bin_directory }}/oc-v{{ sc_okd_release }}-{{ sc_okd_release_minor }} {{ sc_okd_exec_cmd | default("version") }}
    executable: /bin/bash
    chdir: "{{ sc_okd_exec_path | default(omit) }}"
  register: sc_okd_exec_oc_return