---
- name: "delete : Delete symbolic link {{ sc_helm_bin_directory }}/helm"
  ansible.builtin.file:
    path: "{{ sc_helm_bin_directory }}/helm"
    state: absent
  become: sc_helm_become
  tags:
    - delete
    - clients
    - helm
- name: "delete : Delete binary {{ sc_helm_bin_directory }}/helm-v{{ sc_helm_release }}"
  ansible.builtin.file:
    path: "{{ sc_helm_bin_directory }}/helm-v{{ sc_helm_release }}"
    state: absent
  become: sc_helm_become
  tags:
    - delete
    - clients
    - helm
