### REQUIRED
namespace: startxfr
name: client
version: 0.0.1
readme: README.md
license:
- GPL-2.0-or-later
# license_file: 'LICENSE.md'
description: >-
  Collection of ansible roles used for client interaction with running services.
authors:
- Christophe LARUE <clarue@startx.fr>
- Startx dev <dev@startx.fr>
tags: 
- startx
- client
- api
dependencies: {}
# dependencies:
#     "other_namespace.collection1": ">=1.0.0"
#     "other_namespace.collection2": ">=2.0.0,<3.0.0"
#     "anderson55.my_collection": "*" 
repository: https://gitlab.com/startx1/ansible/client
documentation: https://gitlab.com/startx1/ansible/client
homepage: https://gitlab.com/startx1/ansible/client
issues: https://gitlab.com/startx1/ansible/client/-/issues/new
build_ignore:
- '*.tar.gz'
