site_name: STARTX Ansible collection - Clients
site_description: Documentation for the startxfr.client ansible collection
site_author: STARTX
# site_favicon: img/favicon.ico
use_directory_urls: true
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
    - yaml
    - bash
    include_homepage_in_sidebar: false
pages:
- ['index.md', 'Introduction']
- ['roles/ansible.md', 'Ansible role']
- ['roles/aws.md', 'AWS role']
- ['roles/git.md', 'Git role']
- ['roles/helm.md', 'Helm role']
- ['roles/istio.md', 'Istio role']
- ['roles/ocp.md', 'OCP (Openshift) role']
- ['roles/okd.md', 'OKD (Openshift) role']
- ['roles/podman.md', 'Podman role']
- ['roles/terraform.md', 'Terraform role']
- ['roles/vault.md', 'Vault role']
- ['history.md', 'Client project', 'Release history']
- ['contributors.md', 'Client project', 'Contributors']
- ['developpers.md', 'Client project', 'Contributing']
- ['history.md', 'Client project', 'Release history']
markdown_extensions: 
- smarty