site_name: STARTX Ansible collection - Clients
site_description: Documentation for the startxfr.client ansible collection
site_author: STARTX
# site_favicon: img/favicon.ico
use_directory_urls: true
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
    - yaml
    - bash
    include_homepage_in_sidebar: false
nav:
  - Introduction: index.md
  - Collection roles:
      - IAAS:
          - "AWS": roles/aws.md
      - CAAS:
          - "Podman": roles/podman.md
          - "Openshift (OCP)": roles/ocp.md
          - "Openshift (OKD)": roles/okd.md
      - PAAS:
          - "Openshift (OCP)": roles/ocp.md
          - "Openshift (OKD)": roles/okd.md
          - "Helm": roles/helm.md
          - "Istio": roles/istio.md
          - "Vault": roles/vault.md
      - Automation:
          - "Ansible": roles/ansible.md
          - "Terraform": roles/terraform.md
      - CLI:
          - "AWS": roles/aws.md
          - "Podman": roles/podman.md
          - "Openshift (OCP)": roles/ocp.md
          - "Openshift (OKD)": roles/okd.md
          - "Helm": roles/helm.md
          - "Istio": roles/istio.md
          - "Vault": roles/vault.md
          - "Git": roles/git.md
  - Collection project:
      - "Release history": history.md
      - "Contributors": contributors.md
      - "Contributing": developpers.md
markdown_extensions: 
- smarty