---
- name: "exec : oc : Execute the native oc command"
  ansible.builtin.shell:
    cmd: |-
      {{ sc_ocp_bin_directory }}/oc-v{{ sc_ocp_release }} {{ sc_ocp_exec_cmd | default("version") }}
    executable: /bin/bash
    chdir: "{{ sc_ocp_exec_path | default(omit) }}"
  register: sc_ocp_exec_oc_return