---
- name: Create ocp
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  roles:
    - name: Execute the ocp role to install ocp
      role: startxfr.client.ocp
      vars: 
        sc_ocp_action: 'create'
      tags:
        - create
  # tasks: 
  #   - name: Execute the ocp task to install ocp
  #     import_role: 
  #       name: startxfr.client.ocp
  #     vars: 
  #       sc_ocp_action: 'create'
  #     tags:
  #       - create
