---
- name: Delete ocp
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  roles:
    - name: Execute the ocp role to uninstall ocp
      role: startxfr.client.ocp
      vars:
        sc_ocp_action: 'delete'
      tags:
        - delete
  # tasks: 
  #   - name: Execute the ocp task to uninstall ocp
  #     import_role: 
  #       name: startxfr.client.ocp
  #     vars:
  #       sc_ocp_action: 'delete'
  #     tags:
  #       - delete
