---
- name: Create okd
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  roles:
    - name: Execute the okd role to install okd
      role: startxfr.client.okd
      vars: 
        sc_okd_action: 'create'
      tags:
        - create
  # tasks: 
  #   - name: Execute the okd task to install okd
  #     import_role: 
  #       name: startxfr.client.okd
  #     vars: 
  #       sc_okd_action: 'create'
  #     tags:
  #       - create
