---
- name: "delete : Delete symbolic link {{ sc_ocp_bin_directory }}/oc"
  ansible.builtin.file:
    path: "{{ sc_ocp_bin_directory }}/oc"
    state: absent
  become: true
  tags:
    - delete
    - clients
    - oc

- name: "delete : Delete binary {{ sc_ocp_bin_directory }}/oc-v{{ sc_ocp_release }}"
  ansible.builtin.file:
    path: "{{ sc_ocp_bin_directory }}/oc-v{{ sc_ocp_release }}"
    state: absent
  become: true
  tags:
    - delete
    - clients
    - oc

- name: "delete : Delete symbolic link {{ sc_ocp_bin_directory }}/kubectl"
  ansible.builtin.file:
    path: "{{ sc_ocp_bin_directory }}/kubectl"
    state: absent
  become: true
  tags:
    - delete
    - clients
    - kubectl

- name: "delete : Delete binary {{ sc_ocp_bin_directory }}/kubectl-v{{ sc_ocp_release }}"
  ansible.builtin.file:
    path: "{{ sc_ocp_bin_directory }}/kubectl-v{{ sc_ocp_release }}"
    state: absent
  become: true
  tags:
    - delete
    - clients
    - kubectl
