---
- name: "create : Install git{% if (sc_git_release and sc_git_release != 'latest') %}-{{ sc_git_release }}{% endif %} package"
  ansible.builtin.package: 
    name: "git{% if (sc_git_release and sc_git_release != 'latest') %}-{{ sc_git_release }}{% endif %}"
    state: present
  become: true
  when: git_bin_details.rc != 0
  tags:
    - create
    - clients
    - git