---
- name: Initialize ansible context
  import_tasks: "init.yml"
  tags:
    - always
    - init
- name: Create git context
  import_tasks: "create.yml"
  when: sc_git_action == "create"
  tags:
    - create
- name: Delete git context
  import_tasks: "delete.yml"
  when: sc_git_action == "delete"
  tags:
    - delete
