---
- name: "create : Install vault{% if (sc_vault_release and sc_vault_release != "latest") %}-{{ sc_vault_release }}{% endif %} package"
  ansible.builtin.package: 
    name: "vault{% if (sc_vault_release and sc_vault_release != "latest") %}-{{ sc_vault_release }}{% endif %}"
    state: present
  become: yes
  when: vault_bin_details.rc != 0
  tags:
    - create
    - clients
    - vault