---
- name: "create : Install terraform{% if (sc_terraform_release and sc_terraform_release != "latest") %}-{{ sc_terraform_release }}{% endif %} package"
  ansible.builtin.package: 
    name: "terraform{% if (sc_terraform_release and sc_terraform_release != "latest") %}-{{ sc_terraform_release }}{% endif %}"
    state: present
  become: yes
  when: terraform_bin_details.rc != 0
  tags:
    - create
    - clients
    - terraform