---
- name: Initialize ansible context
  import_tasks: "init.yml"
  tags:
    - always
    - init
- name: Create terraform context
  import_tasks: "create.yml"
  when: sc_terraform_action == "create"
  tags:
    - create
- name: Delete terraform context
  import_tasks: "delete.yml"
  when: sc_terraform_action == "delete"
  tags:
    - delete
