---
- name: Initialize ansible context
  import_tasks: "init.yml"
  tags:
    - always
    - init
- name: Create ansible context
  import_tasks: "create.yml"
  when: sc_ansible_action == "create"
  tags:
    - create
- name: Delete ansible context
  import_tasks: "delete.yml"
  when: sc_ansible_action == "delete"
  tags:
    - delete
