---
- name: Delete vault
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  roles:
    - name: Execute the vault role to uninstall vault
      role: startxfr.client.vault
      vars:
        sc_vault_action: 'delete'
      tags:
        - delete
  # tasks: 
  #   - name: Execute the vault task to uninstall vault
  #     import_role: 
  #       name: startxfr.client.vault
  #     vars:
  #       sc_vault_action: 'delete'
  #     tags:
  #       - delete
