---
- name: Create aws
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  roles:
    - name: Execute the aws role to install aws
      role: startxfr.client.aws
      vars: 
        sc_aws_action: 'create'
      tags:
        - create
  # tasks: 
  #   - name: Execute the aws task to install aws
  #     import_role: 
  #       name: startxfr.client.aws
  #     vars: 
  #       sc_aws_action: 'create'
  #     tags:
  #       - create
