---
- name: "delete : Delete symbolic link {{ sc_okd_bin_directory }}/oc"
  ansible.builtin.file:
    path: "{{ sc_okd_bin_directory }}/oc"
    state: absent
  become: "{{ sc_okd_become | default(true) }}"
  ignore_errors: yes
  when: '"oc" in sc_okd_binaries'
  tags:
    - delete
    - clients
    - oc
- name: "delete : Delete binary {{ sc_okd_bin_directory }}/oc-v{{ sc_okd_release }}-{{ sc_okd_release_minor }}"
  ansible.builtin.file:
    path: "{{ sc_okd_bin_directory }}/oc-v{{ sc_okd_release }}-{{ sc_okd_release_minor }}"
    state: absent
  become: "{{ sc_okd_become | default(true) }}"
  ignore_errors: yes
  when: '"oc" in sc_okd_binaries'
  tags:
    - delete
    - clients
    - oc
- name: "delete : Delete symbolic link {{ sc_okd_bin_directory }}/openshift-install"
  ansible.builtin.file:
    path: "{{ sc_okd_bin_directory }}/openshift-install"
    state: absent
  become: "{{ sc_okd_become | default(true) }}"
  ignore_errors: yes
  when: '"installer" in sc_okd_binaries'
  tags:
    - delete
    - clients
    - installer
- name: "delete : Delete binary {{ sc_okd_bin_directory }}/openshift-install-v{{ sc_okd_release }}"
  ansible.builtin.file:
    path: "{{ sc_okd_bin_directory }}/openshift-install-v{{ sc_okd_release }}"
    state: absent
  become: "{{ sc_okd_become | default(true) }}"
  ignore_errors: yes
  when: '"installer" in sc_okd_binaries'
  tags:
    - delete
    - clients
    - installer