---
- name: Initialize ansible context
  import_tasks: "init.yml"
  tags:
    - always
    - init
- name: Create openshift-installer context
  import_tasks: "create.yml"
  when: sc_okd_action == "create"
  tags:
    - create
- name: Delete openshift-installer context
  import_tasks: "delete.yml"
  when: sc_okd_action == "delete"
  tags:
    - delete
